### ISSUE TITLE
Interested in helping with this build

### ISSUE THREAD

**Issue by villalvilla** [mfgbhatti/sun50i-h616-t95-2gb#1]
Hello, I have a TV box exactly like this and I am compiling uboot and kernel from scratch, trying to follow your instructions. Do you have any kind of script or documentation to patch mainline kernel and u-boot from your files? I am trying to follo sunxi's mainline kernel's guide (I have some experience here), but don't have it very clear. Thanks for your help

**Comment by mfgbhatti** [comment]
Hi there, thank you i did not able to boot my box. All this is experimental. It is not a simple straight forward solution. I will update this as i go.
